name: pull-and-push-all
run-name: ${{ github.actor }} is trying pull and push all
on:
  schedule:
    - cron:  '0 8 * * *' # every day at 8 AM UTC (midnight or 1:00 depending on DST)
  workflow_dispatch:


jobs:
  pull-flutter:
    uses: firebase/firebase-docs/.github/workflows/pull-map-and-push-repo.yml@main
    permissions:
      contents: write
    with:
      target_source_repo: https://github.com/firebase/flutterfire.git
      git_commit_user_email: firebase-oss-bot@ossbot.computer
      git_commit_user_name: Firebase OSS Robot
      git_commit_message_text: Pull and push of flutterfire/docs by ${{github.workflow}} run ${{github.run_number}}
      copy_mapping_sources: flutterfire/docs
      copy_mapping_destinations: docs/flutter
# we can add other open source doc repos here/below